### ISSUE TITLE
Possible truncation problem for (real) continuous layers?

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#86] opened 2018-02-06 16:26 UTC
We found a problem during the calculation of the acidity layer, but it might be a more common issue (?)

We noticed that the output for acidity differs from the output we get with the old VBA version of NICHE (see attachment old version = pH grid, new version = Full_dep1tif_acidity.tif). Here are the values we observe for a few problematic pixels:

MLW   |  soil  |  soil_group  |  acidity_old  |  acidity   
-------- |----- |------------- |-------------- |-----
80.9     |  14   |   1         |         2           |         3
110.2  |   11   |   1         |         1         |           2
110.9  |   14  |    1        |          1         |           2

All the problematic pixels have MLW values on the boundary between two classes from soil_mlw_class:

soil_group |  mlw_min | mlw_max|	soil_mlw_class
--------|-------- |-------- | --------
1	       |     -999	   |  80	 |       1
1	       |      80	  |110	|        2
1	      | 110	  |   9000	   |     3

It is not (or not only) a problem of inclusion / exclusion of the boundary: the MLW have been truncated while they should have been rounded off (110.9 should be 111 and thus anyway higher than 110). 
(note that the old version of NICHE required integers als input layers for the groundwater levels, but since real layers did not produce errors, this requirement has sometimes been ignored - as in this example in Grobbendonk)

In addition to this truncation problem, we should check again whether the boundaries should be included or excluded from each class and adapt the current behaviour according to the old VBA version. (my first impression is: the new version excludes the lower boundary and includes the upper boundary in a class _while the old VBA version excludes the upper boundary_ (update 7/2: the conclusion in italic is probably wrong))
[acidity_check.zip](https://github.com/inbo/niche_vlaanderen/files/1699874/acidity_check.zip)

**Comment by johanvdw** [comment] 2018-02-07 08:57
Before looking at the supplied case: The logic around borders that I implemented is described here:
https://inbo.github.io/niche_vlaanderen/codetables.html
I indeed include the upper boundary.

I used this logic as this was a way to reproduce the data from the testcases I had (the handling of boundaries was not described as far as I know).

See also: https://github.com/inbo/niche_vlaanderen/issues/25

**Comment by cecileherr** [comment] 2018-02-07 12:21
Sorry, I was getting confused about these boundaries yesterday :-) 
I am not aware of any documentation about the handling of boundaries in the old VBA niche version, but the old version uses the reclassify function in ArcGIS, en that is what ArcGIS says about it:

>  If a range of values is to be reclassed, the ranges should not overlap except at the boundary of two input ranges. Where overlapping occurs, the higher end of the lower input range is inclusive, and the lower end of the higher input range is exclusive.

My conclusion is that my first impression in my first post was wrong, that is, the VBA version probably also includes the upper boundary (same implementation as in the new version). So if you correct the truncation problem, we should get the same results in the old VBA and in the new version.

**Comment by johanvdw** [comment] 2018-02-07 15:19
The rounding vs truncating has been solved, this was indeed truncating. 

I now still see some differences between both layers (though less). This is because we round before comparing to the table, it seems this did not happen before.

so at position 169993.5 - 210519.35
For soiltype LV (group 2)
MLW: 50.18335723876953  --> 50 --> soil mlw class 4 in the new model
--> 5 in the old model (as it did not round apparently)

If I don't round, I get exactly the same output.

Note we were rounding because I had one example (in Dijle) where pixels with value 15.00000000000001 were considered to be > 15.

I suggest we round up to 0.01. In that case I think we will get a consistent behavior. That is already 1/10th of a mm so any precision below that is definitely rubbish.

**Comment by cecileherr** [comment] 2018-02-07 15:26
Rounding up to 0.01 sounds ok for me!

**Comment by johanvdw** [comment] 2018-02-07 15:32
Disadvantage: if someone rounds to 1cm before using Niche they will get a different response than when they don't round.

**Comment by johanvdw** [comment] 2018-02-07 16:37
Fixed as of fbc58a9e1333463e6ee3f2ecd87c557279d8f398

@cecileherr : you should be able to test this after upgrading to the next alpha version: run 
`pip install niche_vlaanderen==1.0a9`
from an anaconda prompt and redo the analysis (if you have a jupyter notebook open, [restart the kernel ](http://support.datascientistworkbench.com/knowledgebase/articles/857388-how-to-restart-the-jupyter-kernel)to be sure you have the latest version).

**Closed** 2018-02-07 16:44 UTC
