### ISSUE TITLE
Fail when combining config file with absolute path and input layers with relative paths

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#61] opened 2017-11-16 15:09 UTC
* niche_vlaanderen version: 0.0.1
* Python version: 3.6
* Operating System: windows 7

*please define your problem as a python package technical issue or a Niche model question, provide the appropriate label and delete the other section of this template*

## Niche Python Package question
##`niche_package`

### Description

run with config file; absolute path to config file; relative paths for input layers

### What I Did

nv.run_config_file(config= "C://NICHE/niche_config.yaml") #absolute path!

ERROR:rasterio._gdal:CPLE_OpenFailed in b"`C://NICHE\\Input/Mineraalrijkdom/minrijkdom/hdr.adf' does not exist in the file system,\nand is not recognized as a supported dataset name.\n" #error message for first input layer ...

```

## Niche model question
(please add the label  `niche_model` at the right hand side)

Describe your question or issue on the Niche model content (data preparation, model outcomes,...)
#

**Comment by johanvdw** [comment] 2017-11-16 15:13
Can you check with c:/

You should use either c:/ (one slash) or c:\\ (two slashes)

**Comment by cecileherr** [comment] 2018-03-08 10:25
At least with my test datasets, it runs smoothly with "/" everywhere, mixing up absolute and relative paths is not a problem, so I suppose this issue can be closed.

**Comment by johanvdw** [comment] 2018-03-08 13:06
I could not reproduce either, so closing. If it still occurs - please reopen.

**Closed by johanvdw** 2018-03-08 13:06 UTC
Labels: usertests
